
services:
  - type: web
    name: horror-pipeline
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg imagemagick
      pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      # Add your API keys here when ready
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY  
        sync: false
